name: Build/Release Node SDK

on:
  release:
    types: [ released ]
  pull_request:
    branches: [ main ]

jobs:

  enforce_stable_semver:
    name: Require Stable Release Semver
    if: github.event.action == 'released'
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Parse Release Version
        id: parse
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} is a stable release semver ref"
            echo "version=${GITHUB_REF_NAME#v}" | tee -a $GITHUB_OUTPUT
          else
            echo "GITHUB_REF_NAME=${GITHUB_REF_NAME} is not a stable release semver ref" >&2
            exit 1
          fi

  build:
    needs: enforce_stable_semver
    if: always()
    name: Build for Node-${{ matrix.node_ver }} ${{ matrix.config.target }}/${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runs-on }}
    container: ${{ matrix.config.container }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    strategy:
      matrix:
        config:
          - { runs-on: ubuntu-24.04, container: openziti/ziti-builder:v2, target: "linux", arch: "x64" }
        node_ver: [ 20 ]
      fail-fast: false
    
    steps:

    - name: Node Version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_ver }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      #   submodules: recursive
      #   token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Configure Git Authentication
    #   run: |
    #     git config --global url."https://x-access-token:${GITHUB_PAT}@github.com/".insteadOf "https://github.com/"

    - name: Get current zrok repo tag
      if: github.ref_type == 'tag'
      id: tag
      run: echo "TAG=$(git describe --tags --always)" | tee -a $GITHUB_OUTPUT

    - name: Update zrok NodeJS-SDK's package.json version based on current zrok repo git tag
      if: github.ref_type == 'tag'
      run: |
        cd sdk/nodejs/sdk
        npm version ${{ steps.tag.outputs.TAG }} --no-git-tag-version --allow-same-version

    - name: Setup .npmrc
      if: github.ref_type == 'tag'
      # Setup .npmrc file to prepare for possible publish to npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Build the zrok NodeJS-SDK
      run: |
        cd sdk/nodejs/sdk
        npm install
        npm run build
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }}

    - name: NPM Publish
      if: github.ref_type == 'tag'
      run: |
        cd sdk/nodejs/sdk
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
